title: Qiyu Yang # your name (or website title) here
logo: "images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/qiyu-yang-672577222/" class="btn btn--info">LinkedIn</a> 
  <br>
  <a href="/pdf/Qiyu_Yang.pdf"btn btn--info">Resume</ a>  
  <br>
  <a href="https://github.com/Qiyu6769" class="btn btn--info">GitHub</a>  
  <br>

theme: jekyll-theme-minimal
