title: Qiyu Yang # your name (or website title) here
logo: "images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://https://www.linkedin.com/in/qiyu-yang-672577222/">LinkedIn</a> 
  <br>
  <a href="/pdf/Qiyu Yang.pdf" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://https://github.com/Qiyu6769">Github</a>  
  <br>
  
theme: jekyll-theme-minimal
